### ISSUE TITLE
Clicking on Instructions in Navabar doesn't directs us exactly to that section

### ISSUE THREAD

**Issue by zhcet19** [nasa/nasa.github.io#17]

**Comment by zhcet19** [comment]
This  issues  are existing with instructions and related sites sections in navbar

**Comment by JustinGOSSES** [comment]
If anyone wants to fix this, I think you can use CSS for scroll-margin-top as described in: https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-margin-top

**Comment by zhcet19** [comment]
@JustinGOSSES  can you assign me this

**Comment by JustinGOSSES** [comment]
done
