### ISSUE TITLE
Navbar covering topmost paragraph on mobile devices.

### ISSUE THREAD

**Issue by saurabh-33** [nasa/nasa.github.io#25]
Overlapping of navbar with paragraph heading starts at screenwidth <=1000px. 

Adding more padding top for content for smaller devices can help.

<img width="250px" src="https://user-images.githubusercontent.com/60147716/116068557-fda30280-a6a7-11eb-890d-8b0445a1a851.png">
(screenshot captured on iphone X)

**Comment by JustinGOSSES** [comment]
Thanks for the issue @saurabh-33 , this is also mentioned in https://github.com/nasa/nasa.github.io/issues/17

**Comment by VodeniZeko** [comment]
@JustinGOSSES this issue seems to be still open, can I work on it?

**Comment by JustinGOSSES** [comment]
Yes!

**Comment by schmelto** [comment]
oh sorry didn't saw that @VodeniZeko wants to work on this issue.
You can deny my PR and using this from @VodeniZeko instead if he wants to made one 😃
